### ISSUE TITLE
Pipe Read panic with slice bounds out of range

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-storage#623]
When I `Read` and `Write` concurrently by `PipeReader` and `PipeWriter`, I got this panic.

```
panic: runtime error: slice bounds out of range [:147404] with capacity 65536

goroutine 244 [running]:
github.com/beyondstorage/go-storage/v4/pkg/iowrap.(*PipeReader).Read(0xc0001ea238, 0xc00b510000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/lance/go/pkg/mod/github.com/beyondstorage/go-storage/v4@v4.2.0/pkg/iowrap/pipe.go:89 +0x28f
io.(*LimitedReader).Read(0xc00074e9f0, 0xc00b510000, 0x8000, 0x8000, 0x3fcc, 0x0, 0x0)
	/usr/local/go/src/io/io.go:473 +0x63
io.copyBuffer(0x531fb40, 0xc0004a16e0, 0x531d140, 0xc00074e9f0, 0xc00b510000, 0x8000, 0x8000, 0x0, 0x0, 0xdb8fdc8)
	/usr/local/go/src/io/io.go:423 +0x12c
io.Copy(...)
```

This panic can be simply reproducted by code below, with a source file size bigger than `65536`:

```go
	r, w := iowrap.Pipe()

	go func() {
		_, err := src.Read(arg.SrcPath, w)
		if err != nil {
			logger.Error("src read failed", zap.Error(err))
		}
	}()

	_, err := dst.Write(arg.DstPath, r, arg.Size)
	if err != nil {
		logger.Error("write single file failed", zap.Error(err))
		return err
	}
```

However, the range of slice is different every time.

**Comment by Xuanwo** [comment]
I'm investigating this issue, please use `io.Pipe()` until it is resolved.

**Comment by Xuanwo** [comment]
We will remove this function in further release.
